'use strict'

const express = require('express')
const rateLimit = require('express-rate-limit')
const { body } = require('express-validator')

const validate = require('../../middleware/validate')
const ApiError = require('../../lib/ApiError')
const controller = require('./agent.controller')

const router = express.Router()

/**
 * Live booking agent has multiple expensive backends (Tavily, RapidAPI,
 * Amadeus). Per-IP rate limiting protects every endpoint and our API
 * budgets — if a key is missing we still want to bound the OSM/Overpass
 * traffic generated by curious clients.
 */
const liveLimiter = rateLimit({
  windowMs: 60 * 1000, // 1 minute
  max: 30,             // 30 requests / IP / minute across all agent endpoints
  standardHeaders: 'draft-7',
  legacyHeaders: false,
  handler: (_req, _res, next) =>
    next(ApiError.tooMany('Too many live searches. Please wait a few seconds and try again.')),
})

const askLimiter = rateLimit({
  windowMs: 60 * 1000,
  max: 12, // /ask spawns LLM tool-calls + multiple tool runs — costlier
  standardHeaders: 'draft-7',
  legacyHeaders: false,
  handler: (_req, _res, next) =>
    next(ApiError.tooMany('Slow down — the AI is still answering your last question.')),
})

router.post(
  '/trains',
  liveLimiter,
  body('from').isString().trim().isLength({ min: 2, max: 80 }).withMessage('"from" is required'),
  body('to').isString().trim().isLength({ min: 2, max: 80 }).withMessage('"to" is required'),
  body('date').optional({ checkFalsy: true }).isString().trim().matches(/^\d{4}-\d{2}-\d{2}$/).withMessage('date must be YYYY-MM-DD'),
  body('class').optional({ checkFalsy: true }).isString().trim().isLength({ max: 4 }),
  validate,
  controller.trains,
)

router.post(
  '/flights',
  liveLimiter,
  body('from').isString().trim().isLength({ min: 2, max: 60 }).withMessage('"from" is required'),
  body('to').isString().trim().isLength({ min: 2, max: 60 }).withMessage('"to" is required'),
  body('date').optional({ checkFalsy: true }).isString().trim().matches(/^\d{4}-\d{2}-\d{2}$/).withMessage('date must be YYYY-MM-DD'),
  body('return_date').optional({ checkFalsy: true }).isString().trim().matches(/^\d{4}-\d{2}-\d{2}$/).withMessage('return_date must be YYYY-MM-DD'),
  body('passengers').optional().isInt({ min: 1, max: 9 }),
  body('cabin').optional().isString().trim().isIn(['economy', 'premium_economy', 'business', 'first']),
  validate,
  controller.flights,
)

router.post(
  '/hotels',
  liveLimiter,
  body('destination').isString().trim().isLength({ min: 2, max: 80 }).withMessage('destination is required'),
  body('check_in').optional({ checkFalsy: true }).isString().trim().matches(/^\d{4}-\d{2}-\d{2}$/),
  body('check_out').optional({ checkFalsy: true }).isString().trim().matches(/^\d{4}-\d{2}-\d{2}$/),
  body('guests').optional().isInt({ min: 1, max: 8 }),
  body('type').optional().isString().trim().isIn(['any', 'hotel', 'hostel', 'guest_house', 'resort']),
  validate,
  controller.hotels,
)

router.post(
  '/web',
  liveLimiter,
  body('query').isString().trim().isLength({ min: 2, max: 240 }).withMessage('query is required'),
  body('topic').optional().isString().trim().isIn(['general', 'news']),
  body('max_results').optional().isInt({ min: 3, max: 8 }),
  validate,
  controller.web,
)

router.post(
  '/tatkal',
  liveLimiter,
  body('journey_date').isString().trim().matches(/^\d{4}-\d{2}-\d{2}$/).withMessage('journey_date must be YYYY-MM-DD'),
  body('class').optional().isString().trim(),
  validate,
  controller.tatkal,
)

router.post(
  '/ask',
  askLimiter,
  body('message').isString().trim().isLength({ min: 2, max: 1200 }).withMessage('message is required'),
  body('history').optional().isArray({ max: 20 }),
  validate,
  controller.ask,
)

module.exports = router
